# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
pandoc_version: 1.18
python: 2.7

sudo: required
cache: packages

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    
before_install:
  - sudo apt-get install python-pip
  - sudo pip install --upgrade pip
  - sudo pip install fuzzywuzzy
  - sudo pip install python-Levenshtein
  - sudo apt-get install r-base-dev
  - tlmgr install index
  - sudo apt-get update

r_packages:
  - devtools
  - roxygen2
  - testthat
  - reticulate
  - R6
  - covr
  - knitr
  - rmarkdown
  
after_success:
  - Rscript -e 'covr::codecov(quiet = FALSE)'
  
warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change
